### ISSUE TITLE
Ping Google & bing on deploy

### ISSUE THREAD

**Issue by flexbox** [ABrisset/abrisset.github.io#1]
add this `gem 'middleman-sitemap-ping'`

on your `config.rb`

    activate :sitemap_ping do |config|
      config.host = "#{data.settings.site.url}"
    end

Feel free to hack here https://github.com/flexbox/davidl/blob/master/config.rb 

:rocket:

**Comment by ABrisset** [comment]
Thanks for the trick ;)
